### PR TITLE
fix: knowledge delete dialog cleanup

### LINKED ISSUE #871: [Bug]: Incorrect UI behaviour when deleting a knowledge source
### OpenRAG Version

2.3.0.1

### Deployment Method

Podman

### Operating System

macOS

### Python Version

13.3

### Affected Area

Knowledge Filters (partitions, document filtering)

### Bug Description

when I try to delete some knowledge (a URL scan) I get the attached.  Basically, a big box, with content, in the middle of the screen.  It is not scrollable.  So - I am not able to delete this content.  I get this whether I select the delete form the 'three dot' list or from the delete button at the top of the screen.  If I delete a pdf ingestion, it just deletes it

### Steps to Reproduce

1 ingest some data as a URL (I am using a copy of the standard URL ingestion that ingests 2 depth layers of the site vs the standard 1)
2 try to delete the knowledge

### Expected Behavior

The knowledge should be deleted from OpenSearch

### Actual Behavior

I get a box containing some of the chunk of data.  It appears that the box is larger than the screen (there are no upper and lower bounds).
The box is not scrollale, and the only way out is to click back to the screen - which removes the box, but the knowledge is still there.
See screenshot.
Image

### Relevant Logs

```shell

```

### Screenshots

Image

### Additional Context

_No response_

### Checklist

- [x] I have searched existing issues to ensure this bug hasn't been reported before.
- [x] I have provided all the requested information.

### PR DESCRIPTION
**Pull request by philnash**
The knowledge deletion dialog formatting was hard to read and could extend to show too much content. This tidies it all up, turns the bulleted points into a real list, and truncates long file names. Should fix #871.

Before:

delete-dialog-before

After:

delete-dialog-after

### CODE REVIEW

**Comment by philnash** [comment]
> @philnash @Wallgau 
> 
> 
> 
> Small note to have the text sentence case
> 
> Screenshot 2026-02-20 at 8 45 52 AM
> 
> 

Which part is not sentence case?

**Comment by Analuisa1a** [comment]
@philnash, at least from the example listed:
* Delete document
* Delete all

Screenshot 2026-02-20 at 1 47 39 PM

**Comment by philnash** [comment]
Updated!

File: frontend/components/knowledge-actions-dropdown.tsx [hunk 1]
```diff
@@ -151,12 +152,16 @@ export const KnowledgeActionsDropdown = ({
...
         onOpenChange={setShowDeleteDialog}
-        title="Delete Document"
-        description={`Are you sure you want to delete "${filename}"? This will remove all chunks and data associated with this document. This action cannot be undone.`}
+        title="Delete document"
+        description="Are you sure you want to delete this document?"
         confirmText="Delete"
         onConfirm={handleDelete}
         isLoading={deleteDocumentMutation.isPending}
-      />
+      >
```
Comment (Wallgau) [inline frontend/components/knowledge-actions-dropdown.tsx:160]: it wasn't formatted when selected from the dropdown, fixing it here
