### PR TITLE
fix: knowledge upload file types have single source of truth

### LINKED ISSUE #877: [Bug]: onboarding flow, chat input, and knowledge upload support different file types
### OpenRAG Version

0.2.3

### Deployment Method

uvx (uvx openrag)

### Operating System

macOS 26.2

### Python Version

3.13.11

### Affected Area

Ingestion (document processing, upload, Docling), Frontend (Next.js UI, components)

### Bug Description

When going through onboarding, the wizard eventually asks you to ingest a document.

The file types that are available to upload are not documented.

Notably, the [ingestion troubleshooting section](https://docs.openr.ag/ingestion/#failed-or-slow-ingestion) says to make sure you only upload supported file types, but there is no list of supported file types.

The only allowed file types at this onboarding stage are: `.pdf`, `.doc`, `.docx`, `.txt`, `.md`, `.rtf`, `.odt` (https://github.com/langflow-ai/openrag/blob/36bb8f5c280cc6f8252e85b3223ca09c4c63a71b/frontend/app/onboarding/_components/onboarding-upload.tsx#L254)

That list is the same for the chat input (https://github.com/langflow-ai/openrag/blob/36bb8f5c280cc6f8252e85b3223ca09c4c63a71b/frontend/app/chat/_components/chat-input.tsx#L504).

In the knowledge file upload, you can upload the following file types: `.pdf`, `.doc`, `.docx`, `.pptx`, `.ppt`, `.xlsx`, `.xls`, `.csv`, `.txt`, `.md`, `.html`, `.htm`, `.rtf`, `.odt`, `.asciidoc`, `.adoc`, `.png`, `.jpg`, `.jpeg`, `.gif`, `.bmp`, `.tiff`, `.webp` (https://github.com/langflow-ai/openrag/blob/36bb8f5c280cc6f8252e85b3223ca09c4c63a71b/frontend/components/knowledge-dropdown.tsx#L47-L71)

### Steps to Reproduce

1. Go through onboarding
2. Try to upload an .html file

---

1. Go to chat input
2. Try to upload an .html file

---

1. Go to knowledge
2. Try to upload an .html file

### Expected Behavior

You should be able to upload the same file types wherever you are in the system.

### Actual Behavior

You can only upload an .html file in the knowledge section.

### Relevant Logs

```shell

```

### Screenshots

_No response_

### Additional Context

_No response_

### Checklist

- [x] I have searched existing issues to ensure this bug hasn't been reported before.
- [x] I have provided all the requested information.

### PR DESCRIPTION
**Pull request by philnash**
Fixes #877.

Uses the const `SUPPORTED_EXTENSIONS` from the knowledge upload page to make the uploaded file types consistent across all parts of the app.

Added the list of supported file types to the docs too. Gave it a header and linked from the troubleshooting section.

### CODE REVIEW

File: frontend/app/chat/_components/chat-input.tsx [hunk 1]
```diff
@@ -104,13 +105,7 @@ export const ChatInput = forwardRef<ChatInputHandle, ChatInputProps>(
...
 
 		const { getRootProps, getInputProps } = useDropzone({
-			accept: {
-				"application/pdf": [".pdf"],
-				"application/msword": [".doc"],
-				"application/vnd.openxmlformats-officedocument.wordprocessingml.document":
-					[".docx"],
-				"text/markdown": [".md"],
-			},
+			accept: {SUPPORTED_EXTENSIONS.join(",")},
```
Comment (phact) [inline frontend/app/chat/_components/chat-input.tsx]: Looks like this would break the drop zone?

Comment (philnash) [reply frontend/app/chat/_components/chat-input.tsx]: Ah, yeah. I'll go gather the MIME types for all our supported extensions.

File: docs/docs/core-components/ingestion.mdx [hunk 2]
```diff
@@ -36,6 +36,34 @@ You can upload files and folders from your local machine to your knowledge base:
...
+* .asciidoc
+* .adoc
+* .png
+* .jpg
+* .jpeg
+* .gif
+* .bmp
+* .tiff
+* .webp
+
```
Comment (aimurphy) [inline docs/docs/core-components/ingestion.mdx:66]: I wouldn't include these in the docs for two reasons:

1) They can see the list in the app, and it is more relevant at the "point of performance" when they are uploading files.
2) Someone will have to remember to edit this list any time SUPPORTED_FILE_TYPES changes, so it could become misaligned easily.

Comment (philnash) [reply docs/docs/core-components/ingestion.mdx:66]: I don't believe this full list is displayed in the app anywhere and the [troubleshooting page](https://docs.openr.ag/support/troubleshoot#document-ingestion-or-similarity-search-issues) specifically says to "Make sure you ingest only supported file types" without otherwise listing what those are.

As for having to keep the documentation in line with the application, that's true for all features. The logical conclusion to that argument is that we don't have docs at all.

Comment (aimurphy) [reply docs/docs/core-components/ingestion.mdx:66]: oh I apologize. I thought this PR added the list to the UI as well.

Comment (aimurphy) [reply docs/docs/core-components/ingestion.mdx:66]: I am working on another PR to reorganize some of the knowledge content. It will probably conflict with this PR. I will add this list to my PR so it doesn't get lost.

Comment (philnash) [reply docs/docs/core-components/ingestion.mdx:66]: We could add a comment in the code pointing to the list in the docs as a reminder to update the list.

File: frontend/components/knowledge-dropdown.tsx [hunk 3]
```diff
@@ -44,31 +44,25 @@ import {
 import { cn } from "@/lib/utils";
 
 // Supported file extensions - single source of truth
```
Comment (aimurphy) [inline frontend/components/knowledge-dropdown.tsx:46]:
```suggestion
// Supported file extensions - single source of truth
// If modified, please also update the list in the documentation (openrag/docs/docs)
```

Since the content could move, I don't know if it makes sense to point to a specific file.

File: frontend/components/knowledge-dropdown.tsx [hunk 4]
```diff
@@ -44,31 +44,25 @@ import {
...
+  "application/pdf": [".pdf"],
+  "application/msword": [".doc"],
+  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": [".docx"],
+  "application/vnd.ms-powerpoint": [".ppt"],
+  "application/vnd.openxmlformats-officedocument.presentationml.presentation": [".pptx"],
+  "application/vnd.ms-excel": [".xls"],
+  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [".xlsx"],
+  "text/csv": [".csv"],
+  "text/plain": [".txt"],
+  "text/markdown": [".md"],
```
Comment (aimurphy) [inline frontend/components/knowledge-dropdown.tsx:59]: Is .mdx supported?

```suggestion
  "text/markdown": [".md", ".mdx"],
```

Comment (philnash) [reply frontend/components/knowledge-dropdown.tsx:59]: Not according to the Docling Serve component in Langflow.
